blank_issues_enabled: false
contact_links:
  - name: Official Moj Elektro API documentation
    url: https://docs.informatika.si/mojelektro/api/
    about: Check the official public API documentation.
